// Generated by ts-to-zod
import { z } from 'zod'

import {
  zOccultation,
  zLabelStatus,
  zBlocOccultation,
  zObjectId,
  zSuiviOccultation
} from './common.zod'
import { Decision, DecisionCph, UnIdentifiedDecision, UnIdentifiedDecisionCph } from '../types'

export const decisionCphSchema = z.object({
  _id: zObjectId,
  sourceId: z.number(),
  sourceName: z.literal('portalis-cph'),
  originalText: z.string(),
  pseudoText: z.string().optional(),
  zoning: z.record(z.unknown()).optional().nullable(),
  originalTextZoning: z.record(z.unknown()).optional(),
  pseudoTextZoning: z.record(z.unknown()).optional(),
  dateDecision: z.string(),
  dateCreation: z.string(),
  publishDate: z.string().optional().nullable(),
  firstImportDate: z.string().optional().nullable(),
  lastImportDate: z.string().optional(),
  unpublishDate: z.string().optional().nullable(),
  NACCode: z.string(),
  NACLibelle: z.string(),
  endCaseCode: z.string(),
  libelleEndCaseCode: z.string(),
  chamberId: z.string(),
  chamberName: z.string(),
  jurisdictionCode: z.string(),
  jurisdictionId: z.string(),
  jurisdictionName: z.string(),
  selection: z.boolean(),
  sommaire: z.string(),
  blocOccultation: zBlocOccultation,
  occultation: zOccultation,
  recommandationOccultation: zSuiviOccultation,
  // parties: z.undefined(),
  formation: z.union([z.string(), z.undefined()]).optional(),
  // composition: z.undefined(),
  // president: z.undefined(),
  // experts: z.undefined(),
  public: z.boolean(),
  debatPublic: z.boolean(),
  indicateurQPC: z.boolean(),
  // matiereDeterminee: z.undefined().optional(),
  pourvoiCourDeCassation: z.boolean(),
  pourvoiLocal: z.boolean(),
  filenameSource: z.string(),
  labelStatus: zLabelStatus
})

export function hasSourceNameCph(x: UnIdentifiedDecision): x is UnIdentifiedDecisionCph
export function hasSourceNameCph(x: Decision): x is DecisionCph
export function hasSourceNameCph(
  x: Decision | UnIdentifiedDecision
): x is DecisionCph | UnIdentifiedDecisionCph {
  return x.sourceName === 'portalis-cph'
}

export function parseDecisionCph(x: unknown): UnIdentifiedDecisionCph {
  return decisionCphSchema.omit({ _id: true }).parse(x)
}