// Generated by ts-to-zod
import { z } from 'zod'

import {
  zBlocOccultationEnum,
  zLabelStatus,
  zLabelTreatment,
  zObjectId,
  zOccultation,
  zPublishStatus,
  zQualitePartie,
  zSuiviOccultation,
  zTypePartie
} from './common.zod'
import { UnIdentifiedDecision, UnIdentifiedDecisionTj, Decision, DecisionTj } from '../types'

const presidentTJSchema = z.object({
  nom: z.string(),
  prenom: z.string(),
  fonction: z.string(),
  civilite: z.string()
})

const decisionAssocieeTJSchema = z.object({
  idJuridiction: z.string(),
  numeroRegistre: z.string(),
  numeroRoleGeneral: z.string(),
  date: z.string(),
  idDecisionWinci: z.string().optional()
})

const partieTJSchema = z.object({
  type: zTypePartie,
  nom: z.string(),
  prenom: z.string().optional(),
  civilite: z.string().optional(),
  qualite: zQualitePartie.optional()
})

export const decisionTjSchema = z.object({
  _id: zObjectId,
  sourceId: z.number().or(z.nan()),
  sourceName: z.literal('juritj'),
  _rev: z.number().or(z.nan()).optional(),
  __v: z.number().or(z.nan()),
  originalText: z.string(),
  pseudoText: z.string().optional(),
  registerNumber: z.string(),
  dateDecision: z.string(),
  jurisdictionCode: z.string(),
  jurisdictionId: z.string(),
  jurisdictionName: z.string(),
  public: z.boolean().optional(),
  solution: z.string().optional(),
  formation: z.string().optional(),
  labelStatus: zLabelStatus,
  publishStatus: zPublishStatus.optional(),
  labelTreatments: z.array(zLabelTreatment).optional(),
  dateCreation: z.string(),
  publishDate: z.string().optional().nullable(),
  firstImportDate: z.string().optional(),
  lastImportDate: z.string().optional(),
  unpublishDate: z.string().optional().nullable(),
  zoning: z.record(z.unknown()).optional().nullable(),
  originalTextZoning: z.record(z.unknown()).optional(),
  pseudoTextZoning: z.record(z.unknown()).optional(),
  NACCode: z.string(),
  libelleNAC: z.string(),
  NPCode: z.string(),
  libelleNatureParticuliere: z.string(),
  endCaseCode: z.string(),
  libelleEndCaseCode: z.string(),
  chamberId: z.literal(''),
  chamberName: z.literal(''),
  codeService: z.string(),
  libelleService: z.string(),
  debatPublic: z.boolean(),
  indicateurQPC: z.boolean(),
  matiereDeterminee: z.boolean(),
  pourvoiCourDeCassation: z.boolean(),
  pourvoiLocal: z.boolean(),
  selection: z.boolean(),
  sommaire: z.string().optional(),
  blocOccultation: zBlocOccultationEnum,
  recommandationOccultation: zSuiviOccultation,
  occultation: zOccultation,
  president: presidentTJSchema.optional(),
  parties: z.array(partieTJSchema),
  filenameSource: z.string(),
  idDecisionTJ: z.string(),
  idDecisionWinci: z.string().optional(),
  numeroRoleGeneral: z.string(),
  appeals: z.array(z.string()),
  decatt: z.array(z.never()),
  publication: z.array(z.never()),
  decisionAssociee: decisionAssocieeTJSchema.optional()
})

export function hasSourceNameTj(x: UnIdentifiedDecision): x is UnIdentifiedDecisionTj
export function hasSourceNameTj(x: Decision): x is DecisionTj
export function hasSourceNameTj(
  x: Decision | UnIdentifiedDecision
): x is DecisionTj | UnIdentifiedDecisionTj {
  return x.sourceName === 'juritj'
}

export function isDecisionTj(x: unknown): UnIdentifiedDecisionTj {
  return decisionTjSchema.omit({ _id: true }).parse(x)
}
